Project:
  General:
    _Base:
      work_dir:
        value: ./repos/DaCapoExample
        disabled: true
        help: You can customize built-in settings
      config_path:
        value: ./repos/DaCapoExample/config/config.json
        disabled: true
    Group1:
      _help:
        value: This group shows 3 types of setting
      input:
        type: input
        value: someting
        help: type "input" shows a text box
      select:
        option:
          - option1
          - option2
        type: select
        value: option1
        help: type "select" shows a dropdown list
      checkbox:
        type: checkbox
        value: true
        help: type "checkbox" shows a checkbox
Menu:
  Task1:
    _Base:
      priority:
        value: 1
        disabled: true
        help: 0-31, higher number means higher priority
    Group2:
      setting1:
        value: ""
        type: input
        help: settings can be disabled
        disabled: true
      setting2:
        value: ""
        type: input
        help: settings can be hidden
        hidden: true
  Task2:
    Group3:
      _help:
        value: If all settings are hidden, the group will be hidden
      setting1:
        value: ""
        type: input
        hidden: true
      setting2:
        value: ""
        type: input
        hidden: true
